### ISSUE TITLE
too much ping Api to Anker

### ISSUE THREAD

**Issue by Thunder1805** [thomluther/ha-anker-solix#154]
### System Health details

get too much ping 2.2.0 version connection cutboff
![Screenshot_20241103_145810](https://github.com/user-attachments/assets/6e29b4e3-4f75-46cb-a42e-531faf743223)

### Integration version

2.2.0 update have such trouble 

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

via app of Anker no access anymore must wait 24 hours 

### Reproduction steps

1.instsll 2.1 not working today 
2.
3.
...

### Debug logs

```text
soory no logs
```

### Diagnostics dump

sorry

**Comment by kafisc1** [comment]
Same issue here. Maybe an issue with the Anker cloud.

**Comment by Thunder1805** [comment]
hmmm installing version 2.2 and you can see data pull in the panel graphics high, second later zero, then high again. I have 1 Master and 3 guest account. only 1 is showing data, do cloud shouldn't be the issue

**Comment by kafisc1** [comment]
I've just reinstalled the official android App and the issue occurs here also. When starting the Android App I'm getting an error message when typing in the mail adress wihtout even logging in.
![Screenshot_20241103-160952](https://github.com/user-attachments/assets/3d787e4c-da90-4858-b293-00a84514fc2d)

**Comment by thomluther** [comment]
The new integration did nothing change on the connection method.
Yesterday during the day there have been intermittant cloud issues. You have to try again once the cloud is more stable again and your 24h ban is over (or reconnect your router to the internet again to hopefully get a new IP).
And never use the same Anker account on different devices, otherwise you can quickly get to the ban because of too many token changes for your IP address.

**Comment by Thunder1805** [comment]
Now I found out the problem on user side, every time I use the app, either as Master or User, there is a token. When my Handy tells me "Anker is running in the background" and I close "all applications, and then after 1-2 hours log in again Token is used. In HA I uses the Master account log in, therefore each Time on Handy App also a token is made. Then number of token was to much. Now is running fine again, HA with a USER and Handy with Master. Sorry for inconvenience.

**Comment by Thunder1805** [comment]
CLOSE MY COMMENTS

**Comment by thomluther** [comment]
Yeah, this is the issue. Each device using the same account will trigger a new token on the server for that account. After 10 new tokens for the IP per day, there will be the ban for the IP.
You can use the Master account in HA and the Shared account in the App.
A temporary switch is possible when you disable the Api communication in HA with the Api switch entity, then you can login to the App with the Master account and do your stuff. This will trigger a new token for the Master.
Once finished, you can enable the Api switch in HA again and the integration will get a new token again. This will again trigger a new token for the Master account. Your App will be logged off automatically, since the App token is no longer valid.
You can do that 5 times a day before you hit the IP ban...
